#!/usr/bin/env python3
"""Generate rtl/mlkem_zeta_rom.v (blok d: Twiddle Factor Memory, 128 x 12b, 2 read ports)."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from golden_mlkem import ZETAS

root = os.path.join(os.path.dirname(__file__), "..")
lines = []
lines.append("// AUTO-GENERATED by scripts/gen_rom.py -- do not edit.")
lines.append("// Blok d: Twiddle Factor ROM, zeta^BitRev7(i) mod 3329, i = 0..127 (FIPS 203 Appendix A).")
lines.append("// Dual read port, 1-cycle synchronous read (maps to M10K ROM in Quartus).")
lines.append("module mlkem_zeta_rom (")
lines.append("    input  wire        clk,")
lines.append("    input  wire [6:0]  addr0,")
lines.append("    output reg  [11:0] q0,")
lines.append("    input  wire [6:0]  addr1,")
lines.append("    output reg  [11:0] q1")
lines.append(");")
lines.append("    function [11:0] rom;")
lines.append("        input [6:0] a;")
lines.append("        begin")
lines.append("            case (a)")
for i, z in enumerate(ZETAS):
    lines.append(f"                7'd{i}: rom = 12'd{z};")
lines.append("                default: rom = 12'd0;")
lines.append("            endcase")
lines.append("        end")
lines.append("    endfunction")
lines.append("    always @(posedge clk) begin")
lines.append("        q0 <= rom(addr0);")
lines.append("        q1 <= rom(addr1);")
lines.append("    end")
lines.append("endmodule")
open(os.path.join(root, "rtl", "mlkem_zeta_rom.v"), "w").write("\n".join(lines) + "\n")
print("wrote rtl/mlkem_zeta_rom.v")
