// AUTO-GENERATED by scripts/gen_rom.py -- do not edit.
// Blok d: Twiddle Factor ROM, zeta^BitRev7(i) mod 3329, i = 0..127 (FIPS 203 Appendix A).
// Dual read port, 1-cycle synchronous read (maps to M10K ROM in Quartus).
module mlkem_zeta_rom (
    input  wire        clk,
    input  wire [6:0]  addr0,
    output reg  [11:0] q0,
    input  wire [6:0]  addr1,
    output reg  [11:0] q1
);
    function [11:0] rom;
        input [6:0] a;
        begin
            case (a)
                7'd0: rom = 12'd1;
                7'd1: rom = 12'd1729;
                7'd2: rom = 12'd2580;
                7'd3: rom = 12'd3289;
                7'd4: rom = 12'd2642;
                7'd5: rom = 12'd630;
                7'd6: rom = 12'd1897;
                7'd7: rom = 12'd848;
                7'd8: rom = 12'd1062;
                7'd9: rom = 12'd1919;
                7'd10: rom = 12'd193;
                7'd11: rom = 12'd797;
                7'd12: rom = 12'd2786;
                7'd13: rom = 12'd3260;
                7'd14: rom = 12'd569;
                7'd15: rom = 12'd1746;
                7'd16: rom = 12'd296;
                7'd17: rom = 12'd2447;
                7'd18: rom = 12'd1339;
                7'd19: rom = 12'd1476;
                7'd20: rom = 12'd3046;
                7'd21: rom = 12'd56;
                7'd22: rom = 12'd2240;
                7'd23: rom = 12'd1333;
                7'd24: rom = 12'd1426;
                7'd25: rom = 12'd2094;
                7'd26: rom = 12'd535;
                7'd27: rom = 12'd2882;
                7'd28: rom = 12'd2393;
                7'd29: rom = 12'd2879;
                7'd30: rom = 12'd1974;
                7'd31: rom = 12'd821;
                7'd32: rom = 12'd289;
                7'd33: rom = 12'd331;
                7'd34: rom = 12'd3253;
                7'd35: rom = 12'd1756;
                7'd36: rom = 12'd1197;
                7'd37: rom = 12'd2304;
                7'd38: rom = 12'd2277;
                7'd39: rom = 12'd2055;
                7'd40: rom = 12'd650;
                7'd41: rom = 12'd1977;
                7'd42: rom = 12'd2513;
                7'd43: rom = 12'd632;
                7'd44: rom = 12'd2865;
                7'd45: rom = 12'd33;
                7'd46: rom = 12'd1320;
                7'd47: rom = 12'd1915;
                7'd48: rom = 12'd2319;
                7'd49: rom = 12'd1435;
                7'd50: rom = 12'd807;
                7'd51: rom = 12'd452;
                7'd52: rom = 12'd1438;
                7'd53: rom = 12'd2868;
                7'd54: rom = 12'd1534;
                7'd55: rom = 12'd2402;
                7'd56: rom = 12'd2647;
                7'd57: rom = 12'd2617;
                7'd58: rom = 12'd1481;
                7'd59: rom = 12'd648;
                7'd60: rom = 12'd2474;
                7'd61: rom = 12'd3110;
                7'd62: rom = 12'd1227;
                7'd63: rom = 12'd910;
                7'd64: rom = 12'd17;
                7'd65: rom = 12'd2761;
                7'd66: rom = 12'd583;
                7'd67: rom = 12'd2649;
                7'd68: rom = 12'd1637;
                7'd69: rom = 12'd723;
                7'd70: rom = 12'd2288;
                7'd71: rom = 12'd1100;
                7'd72: rom = 12'd1409;
                7'd73: rom = 12'd2662;
                7'd74: rom = 12'd3281;
                7'd75: rom = 12'd233;
                7'd76: rom = 12'd756;
                7'd77: rom = 12'd2156;
                7'd78: rom = 12'd3015;
                7'd79: rom = 12'd3050;
                7'd80: rom = 12'd1703;
                7'd81: rom = 12'd1651;
                7'd82: rom = 12'd2789;
                7'd83: rom = 12'd1789;
                7'd84: rom = 12'd1847;
                7'd85: rom = 12'd952;
                7'd86: rom = 12'd1461;
                7'd87: rom = 12'd2687;
                7'd88: rom = 12'd939;
                7'd89: rom = 12'd2308;
                7'd90: rom = 12'd2437;
                7'd91: rom = 12'd2388;
                7'd92: rom = 12'd733;
                7'd93: rom = 12'd2337;
                7'd94: rom = 12'd268;
                7'd95: rom = 12'd641;
                7'd96: rom = 12'd1584;
                7'd97: rom = 12'd2298;
                7'd98: rom = 12'd2037;
                7'd99: rom = 12'd3220;
                7'd100: rom = 12'd375;
                7'd101: rom = 12'd2549;
                7'd102: rom = 12'd2090;
                7'd103: rom = 12'd1645;
                7'd104: rom = 12'd1063;
                7'd105: rom = 12'd319;
                7'd106: rom = 12'd2773;
                7'd107: rom = 12'd757;
                7'd108: rom = 12'd2099;
                7'd109: rom = 12'd561;
                7'd110: rom = 12'd2466;
                7'd111: rom = 12'd2594;
                7'd112: rom = 12'd2804;
                7'd113: rom = 12'd1092;
                7'd114: rom = 12'd403;
                7'd115: rom = 12'd1026;
                7'd116: rom = 12'd1143;
                7'd117: rom = 12'd2150;
                7'd118: rom = 12'd2775;
                7'd119: rom = 12'd886;
                7'd120: rom = 12'd1722;
                7'd121: rom = 12'd1212;
                7'd122: rom = 12'd1874;
                7'd123: rom = 12'd1029;
                7'd124: rom = 12'd2110;
                7'd125: rom = 12'd2935;
                7'd126: rom = 12'd885;
                7'd127: rom = 12'd2154;
                default: rom = 12'd0;
            endcase
        end
    endfunction
    always @(posedge clk) begin
        q0 <= rom(addr0);
        q1 <= rom(addr1);
    end
endmodule
